sonar.projectKey=miniprojet-devops-backend
sonar.projectName=Mini Projet DevOps - Backend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info